### PR TITLE
Add support for TX51

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Running full parse now to check.

**Comment by curtislacy** [comment]
Okay, both properties appear to be getting parsed & validated, but the filenames don't look right.  Before this PR, I was getting filenames like these:

```
-rw-rw-r-- 1 cmlacy cmlacy 1054 Apr  4 01:56 properties-2.json
-rw-rw-r-- 1 cmlacy cmlacy 1122 Apr  4 01:56 properties-3.json
-rw-rw-r-- 1 cmlacy cmlacy 1050 Apr  4 01:56 properties-4.json
```

Now I'm getting these:

```
-rw-rw-r-- 1 cmlacy cmlacy 1064 Apr  4 02:14 properties-2147483651.json
-rw-rw-r-- 1 cmlacy cmlacy 1175 Apr  4 02:14 properties-2147483652.json
-rw-rw-r-- 1 cmlacy cmlacy 1132 Apr  4 02:14 properties-2147483653.json
-rw-rw-r-- 1 cmlacy cmlacy 1060 Apr  4 02:14 properties-2147483654.json
-rw-rw-r-- 1 cmlacy cmlacy 1215 Apr  4 02:14 properties-2147483655.json
```

Contents look sane at a quick glance, though.

**Comment by curtislacy** [comment]
Hmm, actually it looks like the property IDs really are that huge.  This showed up in the UI:

```
1DYb5Njvcgovt9gUMdMgYkpaQjAEdUooon  4998.43596288 SP2147483651
```

**Comment by ghost** [comment]
Yeah so, the official stance is, every "test" ecosystem property starts on 2147483651, so actually the numbers will have to be adjusted on the UI side; its really a cosmetic enhancement to get them to look right, but the spec actually insists it be this way since they are saving values over 8 bytes of addressable data. See https://github.com/mastercoin-MSC/spec#field-currency-identifier for more detail

**Comment by curtislacy** [comment]
I stand corrected!

**Pull request merged**
