### PR TITLE
Msc parsing and balances

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
```
Add balances for addresses, expand some checks to include smart prope… …    3830397
```

 Faiz Khan  Change currency_str to Smart Property for validation    0db5232

These are the two main commits, intending to address #8

**Comment by ghost** [comment]
Thought I could reopen this with just the changed stuff in another branch, but it depends on the other PR in here

**Comment by curtislacy** [comment]
Yeah, you're working faster than I can review. There's no harm in having the same commits in more than one pr, git'll figure it out in most cases. I'll pull all these together and let them sync tonight, and see what we have tomorrow.

**Comment by curtislacy** [comment]
All right!  Balances!  I see only one address that has any SP on it, so I've put it in this gist: https://gist.github.com/curtislacy/9940236

Issues I see with it:
1. There are three entries for smart properties, but as far as I can tell only two of the four smart properties issued should actually be on this address: https://gist.github.com/curtislacy/9940236#file-1dyb5njvcgovt9gumdmgykpaqjaeduooon-4-2-2014-L101-L103
2. Also, the SP IDs are 1, 4, and 6.  Only four SPs have been issued so that seems incorrect.
3. The TMSC balance (https://gist.github.com/curtislacy/9940236#file-1dyb5njvcgovt9gumdmgykpaqjaeduooon-4-2-2014-L105) appears to map to section 1's balance (https://gist.github.com/curtislacy/9940236#file-1dyb5njvcgovt9gumdmgykpaqjaeduooon-4-2-2014-L24), and SP4 and SP6 balances appear to map to the "4" and "6" sections, but it doesn't look like SP1 (https://gist.github.com/curtislacy/9940236#file-1dyb5njvcgovt9gumdmgykpaqjaeduooon-4-2-2014-L101) actually maps to anything?
4. It's not clear how to map SP4, SP6 to the json files in /www/properties/, but we discussed that already.

**Comment by curtislacy** [comment]
Ah, I stand corrected.... Three of these properties should appear on that address:

```
cmlacy@blockchain-1:/var/lib/omniwallet/www/properties$ grep 1DYb5Njvcgovt9gUMdMgYkpaQjAEdUooon *
properties-05fb1401a1ab7b340d81a0773bf21e62fe7e267511cc366365cc6679268f589f.json:[{"baseCoin": "00", "block": "293484", "color": "bgc-new", "currencyId": 0, "currency_str": "Smart Property", "dataSequenceNum": "01", "details": "unknown", "ecosystem": "02", "formatted_amount": 0, "formatted_ecosystem": 2, "formatted_previous_property_id": 5, "formatted_property_type": 1, "formatted_transactionType": 50, "formatted_transactionVersion": 0, "from_address": "1DYb5Njvcgovt9gUMdMgYkpaQjAEdUooon", "icon": "unknown", "index": "726", "invalid": false, "method": "multisig", "numberOfProperties": "10", "previous_property_id": "00000005", "propertyCategory": "Testing#2", "propertyData": "Test Data", "propertyName": "Test Property 2", "propertySubcategory": "Testing Smart Property#2", "propertyUrl": "mastercoinfoundation.org", "property_type": "0001", "to_address": "unknown", "transactionType": "0032", "transactionVersion": "0000", "tx_hash": "05fb1401a1ab7b340d81a0773bf21e62fe7e267511cc366365cc6679268f589f", "tx_method_str": "multisig", "tx_time": "1396311611000", "tx_type_str": "Fixed property creation", "update_fs": true}]
properties-54188b15313ec245fef98a9875340e4cf4b2a6f48f1ab515dfdf4eda51db3ced.json:[{"baseCoin": "00", "block": "292670", "color": "bgc-new", "currencyId": 0, "currency_str": "Smart Property", "dataSequenceNum": "01", "details": "unknown", "ecosystem": "02", "formatted_amount": 0, "formatted_ecosystem": 2, "formatted_previous_property_id": 3, "formatted_property_type": 1, "formatted_transactionType": 50, "formatted_transactionVersion": 0, "from_address": "1DYb5Njvcgovt9gUMdMgYkpaQjAEdUooon", "icon": "unknown", "index": "450", "invalid": false, "method": "multisig", "numberOfProperties": "499843596288", "previous_property_id": "00000003", "propertyCategory": "Testing", "propertyData": "Test Da", "propertyName": "Test Property 1", "propertySubcategory": "Testing Smart Property", "propertyUrl": "mastercoinfoundation.org", "property_type": "0001", "to_address": "unknown", "transactionType": "0032", "transactionVersion": "0000", "tx_hash": "54188b15313ec245fef98a9875340e4cf4b2a6f48f1ab515dfdf4eda51db3ced", "tx_method_str": "multisig", "tx_time": "1395896090000", "tx_type_str": "Fixed property creation", "update_fs": true}]
properties-e2b6e8bee4ca45197b1a83fc7f4d2b0745620da209aaf79ae96580f40d0fa199.json:[{"baseCoin": "00", "block": "292667", "color": "bgc-new", "currencyId": 0, "currency_str": "Smart Property", "dataSequenceNum": "01", "details": "unknown", "ecosystem": "01", "formatted_amount": 0, "formatted_ecosystem": 1, "formatted_previous_property_id": 0, "formatted_property_type": 1, "formatted_transactionType": 50, "formatted_transactionVersion": 0, "from_address": "1DYb5Njvcgovt9gUMdMgYkpaQjAEdUooon", "icon": "unknown", "index": "783", "invalid": false, "method": "multisig", "numberOfProperties": "1000000", "previous_property_id": "00000000", "propertyCategory": "Companies", "propertyData": "", "propertyName": "Quantum Miner", "propertySubcategory": "Bitcoin Mining", "propertyUrl": "tinyurl.com/kwejgoig", "property_type": "0001", "to_address": "unknown", "transactionType": "0032", "transactionVersion": "0000", "tx_hash": "e2b6e8bee4ca45197b1a83fc7f4d2b0745620da209aaf79ae96580f40d0fa199", "tx_method_str": "multisig", "tx_time": "1395894804000", "tx_type_str": "Fixed property creation", "update_fs": true}]
```

Looks like those SP IDs are coming from incrementing `formatted_previous_property_id` - we talked about this earlier.  Once SP ID assignment is cleared up, my other issues in the previous comment should straighten themselves out.

**Comment by curtislacy** [comment]
Much better!  The only thing that strikes me as goofy is the balance on `1471EHpnJ62MDxLw96dKcNT8sWPEbHrAUe`.  The SP issued to that address looks like it was issued as 500 inseperable tokens, but then the balance on that address is `{ symbol: 'SP3', value: '0.000005' }`.  If the SP is inseperable, we should get a whole number there in the JSON.

**Comment by curtislacy** [comment]
Created https://github.com/mastercoin-MSC/mastercoin-tools/issues/17 to address my last comment, since that has interesting ramifications throughout the system.

**Pull request merged**
