### PR TITLE
Msc maintain properties consistency

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by curtislacy** [comment]
Okay, here's the next one!

```
Traceback (most recent call last):
  File "/home/cmlacy/omniwallet/node_modules/mastercoin-tools/msc_validate.py", line 1715, in <module>
    validate()
  File "/home/cmlacy/omniwallet/node_modules/mastercoin-tools/msc_validate.py", line 1645, in validate
    initial_tx_dict_load()
  File "/home/cmlacy/omniwallet/node_modules/mastercoin-tools/msc_validate.py", line 90, in initial_tx_dict_load
    update_tx_dict(tx_hash)
  File "/home/cmlacy/omniwallet/node_modules/mastercoin-tools/msc_validate.py", line 558, in update_tx_dict
    tx_dict[tx_hash]=load_dict_from_file('tx/'+tx_hash+'.json', all_list=True)
  File "/home/cmlacy/omniwallet/node_modules/mastercoin-tools/msc_utils_general.py", line 160, in load_dict_from_file
    tmp_dict=json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 1 (char 0)
```

**Comment by curtislacy** [comment]
Looks like we didn't close out the file right when we dealt with the earlier exception - `tx/9e8ffcbdc021ffef16f7f694220a3fb18e037e7ecc53ce6039f9841dfa410cbd.json` contains only `[`

**Comment by ghost** [comment]
Hm, are you sure? my tx file for that transaction has:

[{"baseCoin": "00", "block": "296236", "color": "bgc-new", "currencyId": "2147483660", "currencyIdentifierDesired": "2", "currency_str": "Smart Property", "dataSequenceNum": "01", "deadline": "1400198400", "details": "unknown", "earlybirdBonus": "200", "ecosystem": "02", "formatted_amount": 0, "formatted_ecosystem": 2, "formatted_previous_property_id": 0, "formatted_property_type": 1, "formatted_transactionType": 51, "formatted_transactionVersion": 0, "from_address": "1EHdm4svRkVHf9vu7EvJ6aWjwhw7sHUchN", "icon": "unknown", "index": "328", "invalid": false, "method": "multisig", "numberOfProperties": "1", "percentageForIssuer": "20", "previous_property_id": "00000000", "propertyCategory": "Test?", "propertyData": "n/a", "propertyName": "Test?", "propertySubcategory": "Test?", "propertyUrl": "n/a", "property_type": "0001", "to_address": "unknown", "transactionType": "0033", "transactionVersion": "0000", "tx_hash": "9e8ffcbdc021ffef16f7f694220a3fb18e037e7ecc53ce6039f9841dfa410cbd", "tx_method_str": "multisig", "tx_time": "1397701154000", "tx_type_str": "Fundraiser property creation"}]

**Comment by ghost** [comment]
I'll rerun validation, maybe that'll catch it.

**Comment by curtislacy** [comment]
I was, but I'm not sure anymore.  I deleted that file and I'm reparsing the last two days of transactions now - I think I'm going to vindicate you after all.

**Pull request merged**
